
osx_image: xcode9.3
language: objective-c
script:
- xcodebuild test -workspace Example/PixelTest.xcworkspace -scheme PixelTest-Example -sdk iphonesimulator11.3 -destination 'platform=iOS Simulator,name=iPhone X,OS=11.3' ONLY_ACTIVE_ARCH=NO | xcpretty
